services:
  # Backend API
  - type: web
    name: botanalytics-api
    env: node
    plan: free
    buildCommand: cd server && rm -rf node_modules package-lock.json && npm install --no-optional
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=460
      - key: DB_URI
        sync: false
      - key: CLIENT_URL
        value: https://botanalytics-client.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  # Frontend (Static Site)
  - type: web
    name: botanalytics-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://botanalytics-api.onrender.com
